[versions]
agp = "8.7.0"                  # Android Gradle Plugin
junit = "4.13.2"               # Versi JUnit untuk unit test
junitVersion = "1.1.5"         # Versi untuk `androidx.test.ext:junit`
espressoCore = "3.5.1"         # Versi untuk `androidx.test.espresso:espresso-core`
appcompat = "1.7.0"            # AndroidX AppCompat
material = "1.12.0"            # Material Components
activity = "1.9.3"             # AndroidX Activity
constraintlayout = "2.1.4"     # AndroidX ConstraintLayout

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
